info:
  schema_name: dataspace_schema
  schema_version: 0.0.1
  config_name: Trident Dataspace Schema
  config_date: '2025-10-06T12:00:00Z'
  config_version: 0.0.1
connection:
  enabled: False
  username:
  password:
  bucket:
  bucket_folder:
  protocol:
  domain:
  base_path: